language: php
php:
  - "5.4"

branches:
  only:
    - dev

before_script:
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - phpunit -v -c phpunit.xml --coverage-clover build/logs/clover.xml

notifications:
  email: false
